name: 'Signalfx Action'
description: 'Push Signalfx events from GitHub Actions'
author: 'Adapted by Falcon Taylor-Carter. Originaly created by Massimiliano Pippi'
inputs:
  token:
    description: 'A valid Signalfx token'
    required: true
  api-url:
    description: 'The URL of the ingest endpoint, defaults to US datacenter'
    default: 'https://ingest.us1.signalfx.com'
  events:
    description: 'A list of event objects to send, see README for details.'
    default: '[]'
  metrics:
    description: 'A list of metric objects to send, see README for details.'
    default: '[]'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'bar-chart-2'
  color: 'purple'
